version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - /opt/apps/grafana/lib/grafana:/var/lib/grafana
      - /opt/apps/grafana/conf/grafana.conf:/etc/grafana/grafana.conf
    ports:
      - "3000:3000"
    networks:
      - zabbix-net
networks:
  zabbix-net:
    external: true
    #ipam:
    #driver: default
    #config:
    #- subnet: "172.20.240.0/16"

  zabbix-agent:
    ipam:
      driver: default
